{
  Throwable exception=null;
  try {
    runTest();
  }
 catch (  Throwable running) {
    exception=running;
  }
  if (exception != null)   throw exception;
}
