{
  Throwable fail=new AssertionFailedError(message);
  fail.initCause(cause);
  throw fail;
}
